package com.kirakishou.backend.fixmypc.model.net

enum class StatusCode {
    STATUS_UNKNOWN_SERVER_ERROR,
    STATUS_OK,
    STATUS_WRONG_LOGIN_OR_PASSWORD,
    STATUS_LOGIN_ALREADY_EXISTS,
    STATUS_LOGIN_IS_INCORRECT,
    STATUS_PASSWORD_IS_INCORRECT,
    STATUS_ACCOUNT_TYPE_IS_INCORRECT
}